### ISSUE TITLE
Show catalog name in Associations

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#100]
Currently the catalog name is not shown in Product Catalog Associations, so it is not clear and it can't be verified that correct catalog was chosen for the Association.

### Expected behavior
It would be very valuable to display the catalog name, as part of the Association (see screenshot).

![image](https://user-images.githubusercontent.com/7639413/34868218-bc3a1064-f78b-11e7-82a0-58e3a796726e.png)

**Comment by OlegoO** [comment]
Also nice to have same extension for linked category, product in virtual catalog too

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.2
