### ISSUE TITLE
Descriptions without language should be used as fallback

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-catalog#107]
Version info: 
- Module version: 2.21.0

### Expected behavior
If EditorialReview has no language, it should be used as fallback

### Actual behavior
EditorialReview's language property can be null/empty via API/service & required in UI

### Steps to reproduce
1. Create new EditorialReview via API or in code via service
2. Create EditorialReview in UI
3. Try to use first EditorialReview in storefront theme
4. Compare this behaviors. In UI it required, Storefront pass it to theme only if language specified, but via API or service you can successfully leave language not specified.

Behavior should be unified.

**Comment by tatarincev** [comment]
I think the more right solution will to make Language as optional for product editorial reviews. Thus we obtain a default|fallback data for usage on client-side.

**Comment by asvishnyakov** [comment]
@tatarincev What if I have editorial reviews in German, without specified language, but my store is in English?

**Comment by tatarincev** [comment]
That your German description will be paying role as fallback description of the product when there is no English description

**Comment by asvishnyakov** [comment]
@eMazeika Make language optional in UI and use descriptions without language as fallback in storefront
