### ISSUE TITLE
Extension for product associations

### ISSUE THREAD

**Issue by vkrashenko** [VirtoCommerce/vc-module-catalog#112]
Add possibility to request paginated list of associated products separately (now we have the possibility to load association only within the product) with sorting. 

Associations have two types: "Product associations" and "Category associations". If we have category association we need to convert it to multiple product associations (lead to general view product.associations etc.)

**Comment by tatarincev** [comment]
Technical details:
- Need to add new API method `POST api/catalog/products/{0}/associations/search`
- Add new domain models, abstractions, and implementation
![image](https://user-images.githubusercontent.com/7566324/35725534-591591ae-080a-11e8-886e-740fa4d7cad8.png)
- Write unit tests to cover new functionality

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.7
