### ISSUE TITLE
Can add variation into search index

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#118]
Version info: 
- Module version: v2.21.1

### Expected behavior
- Go to admin
- Open and edit variation
- Parent product should be re-indexed.
- Also I should not see Search Index widget for Variation

![image](https://user-images.githubusercontent.com/7639413/36017198-5a91a3a4-0d7f-11e8-85f0-c6b5d82d86b1.png)

**Comment by tatarincev** [comment]
Done
![image](https://user-images.githubusercontent.com/7566324/71519516-82b5b600-28c0-11ea-8999-a26e8386e68d.png)
