### ISSUE TITLE
There is no option to clear the value from a drop-down of the product property

### ISSUE THREAD

**Issue by zhangpengchen** [VirtoCommerce/vc-module-catalog#139]
Version info: 
- Browser version: 
Chrome 66.0.3359.117
- Platform version: 
2.13.26
- Module version: 
2.13.26

### Expected behavior
As a content manager I would like to clear the value from a drop-down of the product property, when I selected the wrong option or the decision wasn't made yet.

### Actual behavior
There is no option to clear the value from a drop-down of the product property at this moment.
See the following screenshot:
![clear](https://user-images.githubusercontent.com/4378651/39474234-45358aa2-4d53-11e8-9591-277cd587a8bd.png)

**Comment by pushnitsa** [comment]
![image](https://user-images.githubusercontent.com/15198683/40366108-9b7af35a-5dd6-11e8-9742-ed5d457e4aa9.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.9
