### ISSUE TITLE
Timeout when calling api/catalog/products

### ISSUE THREAD

**Issue by nickoli4** [VirtoCommerce/vc-module-catalog#156]
Hi,

We've had multiple occasions where calls to the product detail page on a clients website resulted in a 404. This is caused because we get a TaskCanceledException when calling virto using the api/catalog/products endpoint to retrieve the product. When this occurs we also noticed that we cannot open the catalog in the Virto UI either.

I've investigated further and made a memory dump at the time that this issue was occurring. It seems that retrieving the catalog properties from the database takes longer than usual. Because there's a lock around the code that retrieves the catalog, the other requests are also blocked. I've added an analysis report that I generated using DebugDiag (I can also provide a link to the memory dump if necessary):

[minidump (1)_MultipleRules.zip](https://github.com/VirtoCommerce/vc-module-catalog/files/2266901/minidump.1._MultipleRules.zip)

Doing a search for long running requests via the azure portal for our virto database (an azure sql database), we see that the following query (retrieving Property Dictionary Values) sometimes runs for up to 2 minutes (and all calls combined in that hour add up to 24 minutes for 180 calls, which is a lot, considering that the catalog is cached):

SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Alias] AS [Alias], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[Value] AS [Value], 
    [Extent1].[Locale] AS [Locale], 
    [Extent1].[PropertyId] AS [PropertyId]
    FROM [dbo].[PropertyDictionaryValue] AS [Extent1]
    WHERE [Extent1].[PropertyId] IN (N'02E6120C-AB30-45F1-82E4-5B0C60CB195B', N'05FEADCE-B397-45E3-85F9-A60592C03851', N'092697b7-0eaa-482a-9e6e-48abe6b0162c', N'09778DAD-5C2D-4837-845E-B4D66F1D11EC', N'0CD1B4AF-A499-4F0A-98EC-84B1B2F01685', N'0d9d28f1-62fb-4387-9a6b-a9e9678b4ec7', N'1210A091-6698-4BC1-B807-CCAA01AB12FA', N'12C21592-9336-45F5-9D23-1BC7411BFBF3', N'154E0277-8945-465B-893F-6C646414F8F4', N'1D8691C3-ADEC-47B1-82F4-10297DB4A4EB', N'1f3c6c68-637e-477c-ae03-f15f0bb68bd6', N'1FE09B48-553E-4E1C-898E-272BDE4BE63E', N'2A261B61-A5F0-4141-9F21-0F25F136AB4A', N'2DEA1EF2-65DF-4BC9-BC07-BF2C03DA8AED', N'32810357-5B43-4C6A-B711-BD172BC0397D', N'333E68A1-069A-425F-8906-4A6C996713B8', N'37D6BBDF-B1AB-4534-ADFB-5787092DC594', N'39A323B8-F307-43D5-8C1C-6AEF683266A5', N'3DA6FB96-59D8-4044-9229-B169D71D69AE', N'3F146416-F576-4307-8012-63C9BD694F6A', N'3f30ea6d-ed19-4df2-b5b9-5da2ef3e7496', N'43CABC50-630B-4A05-84B9-51E66CFEBBBD', N'44A3DC6F-F58E-4E14-B36D-0DA962F5123B', N'462110db-aa15-4d94-89b8-3471c0d9957e', N'46A18AFF-F9FE-40F9-A9C1-223D622697BB', N'471c77f6-ac35-453c-b286-fc3c98db3804', N'48ada3d6-240d-4cfc-b073-2e834d77e198', N'496aa8d6-edbe-4ff5-913e-dca37294a231', N'4E7C6D72-AA29-4D6D-9A75-C30123C1A1BF', N'51E4C365-D95C-47E1-B2DD-1893F89C70B8', N'66E8BB55-F883-468E-97B0-29C9952FA5D4', N'677311a2-daa4-4060-8ff2-c7225e032b87', N'6b05fbac-f383-48dc-bf09-f13ea57204b9', N'6B0F0350-A60F-4393-BCCF-8D3053168E6C', N'6BCB562F-DD4D-48C1-AEF7-E77DC7CE6111', N'6bf06c8c-752f-4ef0-913b-1018609ab0bb', N'740a0dd7-29c2-4464-a565-26852df527d3', N'7A9B6A6B-4D41-424F-8C0A-8B001DF19C54', N'8828BB75-3199-47CE-8443-40C9BFCD56AE', N'8C6A4E83-48C7-4C01-AA08-3595D1690670', N'8cd54eba-2985-493b-80ec-4680399a24d9', N'90803F69-6DEB-4A6E-AA6E-1483A91C79CF', N'95FEFCA9-CC98-4C48-8F19-79168336D565', N'9F2C59F1-74E5-4A96-8D11-A187F34150CD', N'A2401750-FD85-410F-8D97-B938F40D955C', N'a678aaa4-18c2-4479-bc36-4ba908bfb5d5', N'A75F6382-8582-4997-804E-E4D71C7FE639', N'af9c192c-4201-42ea-99bf-222ca19c5e8f', N'b00087af-ffe7-40ba-abe9-a7829b641a6e', N'B33C60F4-CBF8-4B4E-90C4-46D5B58ED740', N'B828CABF-A4BE-4772-A020-A464C1C3D3DE', N'B93723C7-E937-423A-B4BC-ECF6BC37C6CD', N'BA8D222B-2D56-4229-B66F-77E67B47FE33', N'C11B0D00-20DC-4B9A-A090-A94D52276371', N'C3E7DFF8-DC0A-423D-AF1C-E572F037F8F1', N'c3fcfd6c-18f6-40aa-a520-705df9ce1163', N'C44D7020-8A04-4CB8-B680-5088C00AB8CD', N'c6aea37c-debe-4f8b-8fc0-c73347c8df5d', N'c6df6cca-30e2-4d0a-8b30-aa17d4b8f234', N'c7394d64-c7c5-4971-ab1d-27974fb5d35c', N'cc6c5b1f-c2fc-4ac8-8ada-89a2422a759a', N'CDC14602-A1F2-47C0-96D7-0AA2F0561388', N'D5D8F921-5F2E-42BB-B0B8-D67D987F7B9A', N'DD74E5EF-2352-4142-939A-F113BDF0A9CB', N'ddf5df6a-53de-4cb8-93ed-0c2bc2b444e0', N'DE429C2D-DBB2-469D-87E5-7BD9C04A4D73', N'e59be736-535d-424e-a254-a9a090dc94ce', N'E7743053-FD3C-47AC-80FE-A8BC1A0EA775', N'E890D13D-10C2-48AD-955A-5E33EF06B4A1', N'E9164492-1756-40FF-8BBD-EAD8E1528659', N'EEA20D09-0E65-4AD8-9A66-018C8EA8936F')

Which would explain why other threads have to wait so long to enter the lock. Executing this query myself finishes in 2 seconds at most. What could cause this query to run so long and so often? I can provide a backup of the database if needed.

Platform version: 2.13.27
Module version: 2.21.9

Thanks,

Nick Olivier

**Comment by asvishnyakov** [comment]
#1406

**Comment by nickoli4** [comment]
We actually already have a hangfire job that runs daily to do SQL index and statistics maintenance. We use the following stored procedure on multiple projects:

[AzureSQLMaintenance.zip](https://github.com/VirtoCommerce/vc-module-catalog/files/2269280/AzureSQLMaintenance.zip)

How often would you recommend running your script to rebuild the indexes?

**Comment by asvishnyakov** [comment]
@nickoli4 Daily run is good choice. Did rebuilding indexes help you?

**Comment by nickoli4** [comment]
Well, as I said, we already run this script daily. And it occurred again yesterday, so that doesn't seem to help.

**Comment by tatarincev** [comment]
@nickoli4 Yes, it would be nice to see your data, can you send me the export of your catalog data?
![image](https://user-images.githubusercontent.com/7566324/43882179-0b239fde-9baf-11e8-8e3f-177653eb5351.png)
my email: et@virtoway.com

**Comment by nickoli4** [comment]
I've sent you the export of the catalog data.

**Comment by nickoli4** [comment]
Hi, did you learn anything from the data I sent you?

**Comment by tatarincev** [comment]
@nickoli4  I've replied to your email two times! (you've forgotten to attach your data in the email)

**Comment by nickoli4** [comment]
So it would seem, the replies ended up in my Junk Email folder for some reason... I'll send you a new email.

**Comment by tatarincev** [comment]
@nickoli4  Thanks, I've received your data and successfully reproduced this performance issue on my local machine. Now I'm going to prepare some changes with that and publish release as it will be done.

**Comment by nickoli4** [comment]
That is good news! Could you give us some more context on why and how the issue happens?

**Comment by tatarincev** [comment]
There is fix of your issue https://github.com/VirtoCommerce/vc-module-catalog/commits/dev

**Comment by nickoli4** [comment]
Hi, is there a repro scenario that we can use to test the fix? We were not able to figure out how the performance drop got triggered and it was not happening all the time.

**Comment by tatarincev** [comment]
Yes, just make any changes with catalog structure (edit category or add a new property)

**Comment by nickoli4** [comment]
Combined with the blocked threads we've also seen this result in OutOfMemoryExceptions when we don't restart the application. When checking what's in memory in the memory dump which I used to debug this issue (using !dumpheap -stat in WinDbg) we found the following entries:

[memory.txt](https://github.com/VirtoCommerce/vc-module-catalog/files/2331665/memory.txt)

There seem to be a lot of PropertyDictionaryValue objects on the heap. Am I right in thinking this is suspicious and, will it be solved by this fix?

**Comment by tatarincev** [comment]
@nickoli4  I'll check and let you know when will having some information

**Comment by tatarincev** [comment]
@nickoli4 I have been made the new commit into dev branch related to your issue.  https://github.com/VirtoCommerce/vc-module-catalog/commit/1847ae6a9af5d3751107ec17b5d7acfa5dcae1e1 Now, all have to work fine.

**Comment by nickoli4** [comment]
Could you give me a summary of what has changed with the two fixes and what was the root cause for the performance issues?

**Comment by tatarincev** [comment]
Yes, sure. There were a redundant dictionary values loading for all catalog properties and store them in the cache. I've just removed this data from pre-loading and cache logic. 
These changes are  backward compatible  and I guess you might update your module absolutely safe after module being release

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/v2.22.0

**Comment by tatarincev** [comment]
There are breaking changes in https://github.com/VirtoCommerce/vc-module-catalog/releases/v2.22.0 version I've to revert back these changes and continue to work on this issue in another branch
https://github.com/VirtoCommerce/vc-module-catalog/tree/property-dictionary-redesign

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.0

**Comment by tatarincev** [comment]
Seems I've completely resolved your performance issue  please update your catalog modules to the latest version https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.1

The main reason for this problem was that the platform has a constructive defect in the catalog module is consisted of redundant re-loading of dictionary values of properties in the memory cache after each catalog structure change. We eliminated this logic in the 2.23.0 version.

And another 'not main' reason was in that fact what your DB contains a huge amount of duplicated dictionary values of properties. We also took into account these case and included in 2.23.1 version the special SQL migration which will remove duplicated records from the database.
