### ISSUE TITLE
Catalog export failed on 404 error

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-module-catalog#161]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: 
- Platform version: 2.13.35
- Module version: 2.21.9

### Expected behavior
I should successfully export catalog with binaries even if any external resources are missing. It would be nice to see Warning, but not error and operation failure.

### Actual behavior
I successfully exported catalog without binaries (pictures?), but it fails if the same catalog with Binaries included. 
Export fails with error:
VirtoCommerce.Catalog: The remote server returned an error: (404) Not Found.
 The remote server returned an error: (404) Not Found.

### Steps to reproduce
1.
2.
3.

**Comment by anton-abyzov** [comment]
http://take.ms/c7HWx - demo of how it shows (quite short time of showing the message with warnings)

**Comment by anton-abyzov** [comment]
fixed this by adding platform PR, for multiple errors it looks like - http://take.ms/uDVSg

**Comment by anton-abyzov** [comment]
resolved this by adding PR to platform, for multiple erros it looks like -  http://take.ms/uDVSg
