### ISSUE TITLE
Keep image category when creating a new image

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#17]
Version info: 
- Browser version: Any
- Module version: v2.18.7

### Expected behavior
Keep image category when creating a new image

### Actual behavior
I don't see any effect

### Steps to reproduce
1. Go to product images
2. upload image and set image category and language 
![image](https://user-images.githubusercontent.com/7639413/28794144-98a34d8c-7635-11e7-9cde-cf57991440b8.png)

3. save
![image](https://user-images.githubusercontent.com/7639413/28794162-a6daf0e4-7635-11e7-884d-edf9fb53378f.png)

**Comment by ksavosteev** [comment]
![image](https://user-images.githubusercontent.com/20122385/29016967-fe7fc562-7b54-11e7-92a2-cd9c80285a8c.png)
