### ISSUE TITLE
Dictionary property value doesn't save if  value has been reset at least once 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-catalog#176]
Open product properties widget
Click `reset values` action  for any of dictionary property
Choose then any value from the dropdown and click save
The empty value will be saved

Expected:
The latest selected dictionary value must be saved.

**Comment by anivirtoway** [comment]
@tatarincev  Can't reproduce issue. Can you provide detail steps of concrete product please?

**Comment by tatarincev** [comment]
It seems this bug has already been fixed.
