### ISSUE TITLE
Provide ability to edit Image Category and language 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#18]
Provide ability to edit Image Category and language 

Version info: 
- Module version: v2.18.7

### Expected behavior
Provide ability to edit Image Category and language 

### Actual behavior
![image](https://user-images.githubusercontent.com/7639413/28794246-f8d1e556-7635-11e7-9839-e04416aac6cb.png)

**Comment by ksavosteev** [comment]
![image](https://user-images.githubusercontent.com/20122385/29017009-2bd65a94-7b55-11e7-8b41-2bb32f65311d.png)
