### ISSUE TITLE
CatalogModuleListEntryController always searches for products when only listing categories.

### ISSUE THREAD

**Issue by WimVergouwe** [VirtoCommerce/vc-module-catalog#180]
We're using the CatalogModuleListEntryController to list categories, but the controller always looks for products as well.

See: 
https://github.com/VirtoCommerce/vc-module-catalog/blob/e091de9dc410fb0cd678944b72430dca8dfd8112/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleListEntryController.cs#L86

Can this be fixed, it has negative impact on the performance?

**Comment by tatarincev** [comment]
I think we can remove this forcing behavior from here

**Comment by WimVergouwe** [comment]
@tatarincev , ok, cool. Do you expect me to send a PR?

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.12
