### ISSUE TITLE
SEO urls for removed products should be saved and return 410 error code

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-catalog#181]
Currently, if we will remove the product, storefront will simple return 404 when search bot will try to index this page. Instead, 410 error code ("gone") should be returned, which will cause to remove this product from search faster and stop trying to reindex this page.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-94
