### ISSUE TITLE
va-property2 - Multi language property setter

### ISSUE THREAD

**Issue by Tilesto** [VirtoCommerce/vc-module-catalog#184]
My case:
I have multi language property, for example -
Property - Name
Languages - ['fi-FI', 'sv-SE', 'no-NO'].

I need use va-property2 directive only for one language. I doing (pseudocode):
```
<va-property2 ng-model="entity.name" get-prop-values="getPropValues"
languages="['sv-SE']" default-language="'sv-SE'"></va-property2>
```
I pass on va-property2 only 1 language.
But if i change (from `<input/>`) value of property - my Name property will have only 1 language (not 3 as on start).
I think it happens because :
![image](https://user-images.githubusercontent.com/28765507/49631908-784a2500-f9fc-11e8-934b-5f295e00db11.png)

Version info: 
- Browser version: all
- Platform version: 2.13.35
- Module version: 2.21.9

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/49637385-e64b1800-fa0d-11e8-8b6a-cdc03fd62d0e.png)
Please use the latest actual module version v2.23.12 instead of old legacy and no longer supporting.

**Comment by asvishnyakov** [comment]
@tatarincev This is not about display information, but about save instead:

>  if i change (from <input/>) value of property - my Name property will have only 1 language

**Comment by Tilesto** [comment]
PR https://github.com/VirtoCommerce/vc-module-catalog/pull/186

**Comment by sansey2k** [comment]
@tatarincev We are waiting for urgent release. It  blocks our current development tasks. Client expectation is to have it ASAP

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.13
