### ISSUE TITLE
 possibility to define sort order of dictionary values, besides ascending and descending.

### ISSUE THREAD

**Issue by pungiish** [VirtoCommerce/vc-module-catalog#185]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Any
- Platform version: Any
- Module version: Any

### Expected behavior
In the storefront, to define the sort order of dictionary values, instead of only having the ascending/descending option. Useful for clothing sizes (S, M, L, XL), etc..
### Actual behavior
dictionary values only sorted alphabetically, IE. L M S XL, which looks weird.
@tatarincev

**Comment by artem-dudarev** [comment]
I don't like the `Priority` property name. Dictionary items are equal, they just need to have custom order.
Also this name means that first elements should have bigger numbers which is not convenient.
I prefer `SortOrder` or `Position`.

**Comment by tatarincev** [comment]
Ok, I've just checked we use `SortOrder` property name for this purposes in catalog. So lets be `SortOrder` then

**Comment by Andrew-Orlov** [comment]
https://github.com/VirtoCommerce/vc-module-core/pull/103

**Comment by Andrew-Orlov** [comment]
![image.png](https://images.zenhubusercontent.com/56b873cb6caf56c9d38c4e91/921c263c-feea-49c5-9235-6cf0b153a681)

https://github.com/VirtoCommerce/vc-module-catalog/pull/187

**Comment by artem-dudarev** [comment]
Actually our real goal is to use this `SortOrder` value when using indexed search for products and the sorting is performed by a property that is a dictionary.
For example, if we have products with `Color` property and `White` color has `SortOrder=1` and `Black` color has `SortOrder=2`, then when we search for products and sort them by `Color`, then white products should be returned first.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/v2.23.13
