### ISSUE TITLE
Allow to manage category display order through UI

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-catalog#188]
**Functional requirements:**
Need to have possibility to manage category display order. The category priority can be used for sort order in client applications such as VC storefront. 

**Technical details:**
The `Category`  domain model already has a `Priority` property  just need to display it on the Category details blade 
![image](https://user-images.githubusercontent.com/7566324/50237898-b5cc8c00-03c6-11e9-8d71-2f1f82963555.png) and check what entered values is stored in database.

**Comment by yecli** [comment]
Released in [v2.23.14](https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.14)
