### ISSUE TITLE
Removing SKU restrictions

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog#198]
Following symbols could not be a part of product/variation SKU now: "[$+;=%{}[\]|\\\/@ ~!^*&()?:'<>,]".

We could remove these symbols from restrictions without security loss: "\\", "/", " ", ":".

- Module version: 2.23.13

### Expected behavior
These symbols "\\", "/", " ", ":" are valid for products/variations/categories SKU's.

### Actual behavior
SKU cannot contain these symbols.

### Steps to reproduce
1. Open catalog, try to create new product/variation/category.
2. Enter SKU containing one of the symbols described above.
3. Save changes.

**Comment by ilyawzrd** [comment]
![sku](https://user-images.githubusercontent.com/22875828/53025685-09f8f880-346a-11e9-8ddf-f15851c29073.gif)

**Comment by yecli** [comment]
Released in [v2.23.14](https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.14)
