### ISSUE TITLE
Can close Edit Description blade without confirmation 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#20]
I can close Edit Description blade without confirmation.
Bad UI|UX, I suggest to move Save|Cancel button into toolbar 

Version info: 
- Browser version:  Chrome
- Module version:  v2.18.7

### Expected behavior
Open  Edit Description, VC should ask warning confirmation, I want to close blade when exit/close with edited description.

### Actual behavior
Can close blade without confirmation and lost data

### Steps to reproduce
1. Open product
2. Open descriptions
3. Edit text
4. Close blade 

![image](https://user-images.githubusercontent.com/7639413/28794924-5b4af496-7638-11e7-98bc-1bec4fd02670.png)

**Comment by asvishnyakov** [comment]
I.e. set `blade.isClosingDisabled` to true in ok-cancel templates

**Comment by ksavosteev** [comment]
![image](https://user-images.githubusercontent.com/20122385/29016953-d8f9eff2-7b54-11e7-88f4-2942411aeb9e.png)
