### ISSUE TITLE
Error: Invalid object name 'SeoUrlKeyword'

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-catalog#203]
We have a separate database for the catalog module. When I try to delete a product or a category I get the error `Invalid object name 'SeoUrlKeyword'.`

Also, I can't see the error details in the UI.

Version info: 
- Platform version: 2.13.41
- Module version: 2.23.13

![image](https://user-images.githubusercontent.com/8775253/53869900-cb367700-4001-11e9-8684-72ee63bff8f8.png)

**Technical details:**
Need to remove SeoUrlKeyword manipulation from [CatalogRepositoryImpl](https://github.com/VirtoCommerce/vc-module-catalog/blob/aaac917256e9033d7247e04130a6130bfec10b77/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L403). This logic should be handled [ItemServiceImpl](https://github.com/VirtoCommerce/vc-module-catalog/blob/61ea9d59f4837d36c08c3f0495c1320920882001/VirtoCommerce.CatalogModule.Data/Services/ItemServiceImpl.cs#L114) for Product and in CatalogServiceImpl for category using ICommerceService.

For proper error appearance need to remove [custom error handling](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js#L217) to allow common error interceptor to work.

**Comment by yecli** [comment]
Released in [v2.23.18](https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.18).
