### ISSUE TITLE
I need to be able to set filtered browsing view/edit permissions in admin

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-module-catalog#206]
In order to be able to set filtered browsing permissions through the admin I need next permissions to be added to the module manifest:
"catalog:BrowseFilters:Read"
"catalog:BrowseFilters:Update"

https://github.com/VirtoCommerce/vc-module-catalog/blob/aaac917256e9033d7247e04130a6130bfec10b77/VirtoCommerce.CatalogModule.Web/module.manifest#L121

Here is the check of permissions:
https://github.com/VirtoCommerce/vc-module-catalog/blob/61ea9d59f4837d36c08c3f0495c1320920882001/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs#L59

https://github.com/VirtoCommerce/vc-module-catalog/blob/61ea9d59f4837d36c08c3f0495c1320920882001/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogBrowseFiltersController.cs#L89

**Comment by yecli** [comment]
Released in [2.23.17](https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.17).

**Comment by yecli** [comment]
@aartiomov Could you tell if you satisfied with the functionality?
Also could you describe the usage (e.g. screenshot)?
