### ISSUE TITLE
Can't browse found category

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-module-catalog#213]
Version info:
- Module version: latest

### Expected behavior
Can find category by keyword and browse its content.
### Actual behavior
Clicking on found category does nothing
### Steps to reproduce: http://recordit.co/GQW0RKpPnR
1. search for category by keyword
2. clock on found category

**Comment by yecli** [comment]
Seems #1512 is the same one.

**Comment by yecli** [comment]
Released in [2.23.17](https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.17).
