### ISSUE TITLE
Add an ability to have Assets on Catalog and Category

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog#217]
Need to add an ability to have Assets on Catalog and Category. like for product:
![image](https://user-images.githubusercontent.com/15610352/56353094-14294000-61ea-11e9-956f-f820f5893a3a.png)

**Technical details:**
Could be done like for images with `IHasImages`, but in our case we need `IHasAssets` for `Category` and `Catalog` models:
https://github.com/VirtoCommerce/vc-module-catalog/blob/aaac917256e9033d7247e04130a6130bfec10b77/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L101-L103
https://github.com/VirtoCommerce/vc-module-core/blob/025ae6e5722f49033899122994c9a65aad22d5fe/VirtoCommerce.Domain/Catalog/Model/Category.cs#L7

Extension should be done on all levels: from database to UI.

**Comment by yecli** [comment]
Related to https://github.com/VirtoCommerce/vc-platform/issues/1569.

**Comment by pixellos** [comment]
Hi, it would be nice if there would be category, like Images does have, or maybe tags like associations

**Comment by 5309** [comment]
@pixellos Can you please explain the context of why you need folders or tags for Catalog / Category assets and describe how are you going to use it (use case or user story). Having it I can include the request into the platform backlog and assign a proper priority to it.

**Comment by pixellos** [comment]
@5309 Hi

Category is grouping products, we're using it like product family - For example we have TVs: LG UltraColor 9999 and LG UltraColor 9998 (I made up those names), and there are some technologies used at whole product family, and in assets we're gonna group assets into Certificates, Brochures, Pricelists, Leaflets, Warianty disclaimers (those would be those tags) and it would be a lot redundant to upload it in each product separatelly

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-97
