### ISSUE TITLE
Field MainProductId doesn't exist in product object returned from API.

### ISSUE THREAD

**Issue by adminoren** [VirtoCommerce/vc-module-catalog#218]
In storefront I have variationId, and I need to know the Id of the main product, but I can't do it. There is no field MainProductId in product model which comes from API of the catalog module.

**Comment by tatarincev** [comment]
@adminoren The current product web model already has `TitualProductId` property with the same meaning as `MainProductId` in domain product model, please use it on the storefront side.
https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web.Core/Converters/ProductConverter.cs#L117

**Comment by adminoren** [comment]
Thanks, @tatarincev! Name of the field is not obvious, I expected something like main.. or parent... Have gone to refactor code :)
