### ISSUE TITLE
Query optimization based om empty collections 

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog#224]
Need to optimize GetByIds methods by skipping redundant requests in case of empty collections like in [Cart module](https://github.com/VirtoCommerce/vc-module-cart/pull/35/files).

Places where need to do optimization:
[GetCatalogsByIds](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L174)
[GetItemByIds](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L233)
[GetPropertiesByIds](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L320)
[GetAllCatalogProperties](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L341)
[GetPropertyDictionaryItemsByIds](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs#L631)

As proposed by @asvishnyakov and @artem-dudarev, we could add [IQueryable<> extension method](https://github.com/VirtoCommerce/vc-module-catalog/issues/224#issuecomment-486136280) to platform that implements this logic and use it in this cases.

**Comment by asvishnyakov** [comment]
I would like to have extension method and use method chain instead of if-wrapping, i.e.
result = Cart.NotNull.Where(...).ToArray();

**Comment by yecli** [comment]
Not clear how to do this, as our goal here in not just to ensure that IEnumerable<> is not null or empty, but to skip queries execution in that case. Could execution of query be skipped in extension method?

**Comment by artem-dudarev** [comment]
I do it this way:
```csharp
public class MyRepository
{
        public virtual IList<CarouselBannerEntity> GetCarouselBannersByIds(IList<string> ids)
        {
            return CarouselBanners
                .Where(x => ids.Contains(x.Id))
                .LoadWithRelatedEntities(ids, LoadCarouselBannerRelatedEntities);
        }

        protected virtual void LoadCarouselBannerRelatedEntities(IList<string> ids)
        {
            CarouselBannerStores.Where(x => ids.Contains(x.CarouselBannerId)).Load();
            CarouselBannerUserGroups.Where(x => ids.Contains(x.CarouselBannerId)).Load();
        }
}
```
```csharp
public static class QueryableExtensions
{
    public static IList<T> LoadWithRelatedEntities<T>(this IQueryable<T> query, IEnumerable<string> keys, Action<IList<string>> loadRelatedEntitiesAction)
        where T : Entity
    {
        IList<T> result;

        if (keys?.Any() == true)
        {
            result = query.ToList();

            if (result.Any())
            {
                var ids = result.Select(x => x.Id).ToList();
                loadRelatedEntitiesAction(ids);
            }
        }
        else
        {
            result = new T[0];
        }

        return result;
    }
}
```

**Comment by yecli** [comment]
Yes, wanted to change that too.

**Comment by yecli** [comment]
After discussion with @tatarincev decided to not use extension method and handle references loading in place.
