### ISSUE TITLE
SQL long time request executions with null passed as itemId to ItemServiceImpl.GetById() method

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-catalog#230]
Seems this issue already has  been fixed by https://github.com/VirtoCommerce/vc-module-catalog/pull/227 but need to check to be ensure.

How to reproduce:
Pass null as itemId into https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Services/ItemServiceImpl.cs#L45

**Comment by OlegoO** [comment]
I call service with these parameters
[10:03 AM] Oleg Zhuk
    
GetById с itemId == null сводит систему TCS с ума ответ идет 60 секунд, сжирается кучу памяти 

var product = _itemsService.GetById(model.Id, ItemResponseGroup.ItemLarge | ItemResponseGroup.ItemAssociations | ItemResponseGroup.ItemProperties);

**Comment by yecli** [comment]
Optimized service methods as there were redundant queries even with optimized repository methods.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.19
