### ISSUE TITLE
Exception on adding Mapping when no category is selected

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog#234]
Exception is thrown when we are adding mappings for all categories (selected by "select all" checkbox) to virtual catalog
"Target catalog and category identifiers should be specified."

### Expected behavior
There should be no exception, links should be created.

### Actual behavior
![image.png](https://images.zenhubusercontent.com/5c04f7fce608ff4e3ebcc826/682c4509-76e2-46ff-8df7-404f91d3a724)
![image.png](https://images.zenhubusercontent.com/5c04f7fce608ff4e3ebcc826/43e39db6-ea8b-471e-b399-108fe31ebfdd)
### Steps to reproduce
1. Go to virtual catalog (Important!: do not select specific category)
2. Add\Link
3. Select catalog, select all categories (using select all checkbox) from some category or catalog, press Map.

Reason:
We could have empty [blade.parentBlade.categoryId](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web/Scripts/blades/categories-items-list.js#L251) if we do not select category.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.21
