### ISSUE TITLE
Allow to use comma in term values for indexed search

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-catalog#235]
**Describe the bug**
For example, I want to search products with name _"Railway, Service Trucks, Shipboard Equipment, Mining". When I pass this value to the catalog product search API i'm using the Terms property to apply this filter.  The filter is built up by comma separating the multiple values in the group. If commas in the value are supported how should I escape them?

**Steps to reproduce**
POST http://localhost/admin/api/catalog/search/products
{"storeId":"Electronics", **"terms": ["__content:Beats, by, Dre Solo 2 On-ear Headphones"],** "sort":"name:asc","skip":0,"take":50}

The problem in  this class   
https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Data/Search/SearchCriteriaExtensions.cs#L63 it uses the  ',' char as multi-value delimiter and produces an array of values for given term value. This leads to construct invalid search request and result because all data stored in index with commas.
![image](https://user-images.githubusercontent.com/7566324/62051673-24eb4800-b214-11e9-8a47-03664868e0b4.png)

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.22
