### ISSUE TITLE
Can't add product to virtual catalog when product found via search

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-catalog#24]
In gitter client says:

> Found a bug in adding product to virtual catalog with search: Virtual Catalog -> Add -> Link -> Select Catalog -> Search in catalog -> Select Product -> Link -> No product is added to virtual catalog
> Not doing the search part, looking for it and selecting and link works fine

**Comment by artem-dudarev** [comment]
Actually the product is added to the virtual catalog but it is not displayed in the list.
Fixed with d3d6ea599d77ce5c78b7883ec932742ab72765bc

**Comment by artem-dudarev** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.19.1
