### ISSUE TITLE
AggregationItem.IsApplied in searchResult is always false. 

### ISSUE THREAD

**Issue by adminoren** [VirtoCommerce/vc-module-catalog#240]
When product search criteria contains terms, I expect that IsApplied flag of some AggregationItems will be true, but it is always false.
Our workaround in storefront: 
`
foreach (var aggregation in criteria.Terms.GroupBy(t => t.Name))
                {
                    searchRes.Aggregations.Where(agr => agr.Field.EqualsInvariant(aggregation.Key))
                        .SelectMany(x => x.Items)
                        .ToList()
                        .ForEach(c => c.IsApplied = aggregation.Any(i => c.Value.Equals(i.Value)));
                }
`

**Comment by tatarincev** [comment]
Unfortunately this functionality doesn't have trivial implementation on the current search architecture, and  will be added to the requirements of the future search engine.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-47
