### ISSUE TITLE
How to make variations from product properties automatically?

### ISSUE THREAD

**Issue by dku4cdm** [VirtoCommerce/vc-module-catalog#243]
### Description

We have products with three and more variation properties. Each variation property contains a lot of type like a color (black, aqua, white, etc.). How can I make fast variations for all of the combinations from these variation properties? 

(For some products, the whole number of variations can be over than 15 thousand, and make it manually is not an adequate variant for me)  

## For example: 

**Color**       black, white, green
**Emblem**  num1, num2, num3

## After creation:

black-num1, black-num2, black-num3
white-num1, white-num2, white-num3
green-num1, green-num2, green-num3

**Comment by Woland2k** [comment]
Do you need to keep inventory for each variation or is the actual variation created on demand when customer orders the configured item? If it is on-demand, then it might be easier to add configurator instead of creating variations.

**Comment by tatarincev** [comment]
@dku4cdm  Thanks for detailed feature request description.
You question is refers to the “Cartesian product” in order to generate set of product variations from multiple sets of properties and their values. At this moment we don't have such functionality out the box, but we have putted your request into our backlog and will be considered within our development process cycle.

**Comment by dku4cdm** [comment]
Ok, we will wait for this feature implementation. @Woland2k interesting idea with a configurator, I will try to use it for now.

**Comment by Woland2k** [comment]
@dku4cdm it really depends on other requirements you might have, primary if you need to set different pricing or inventory levels per SKU

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-99
