### ISSUE TITLE
Select all when adding products to virtual catalog only selects 20 in view

### ISSUE THREAD

**Issue by bjornstromblom** [VirtoCommerce/vc-module-catalog#25]
When selecting products for a virtual catalog the "check all checkbox" will only select the 20 products in view. I have about 500 products to add. So i need to add/map 20, go to the next page, map 20 and so on. The UI "locks up" when i do this so some times i need to go back, search again and start over.

I would love it if check all checkbox gave me all of the search results to map for my virtual catalog.

**Comment by bear133** [comment]
Sounds like your moving in the right direction!

**Comment by tatarincev** [comment]
See as example this commit:
https://github.com/VirtoCommerce/vc-module-customer/commit/2be87d43b71deb0ba37413e60624debb2b72dd9c

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.9
