### ISSUE TITLE
Replace the Flags as label for culture name label to the culture names

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-catalog#250]
![image](https://user-images.githubusercontent.com/7566324/64600474-795d1800-d3bb-11e9-8754-5ddb097e8516.png)
![image](https://user-images.githubusercontent.com/7566324/64600882-32235700-d3bc-11e9-9050-634979217d76.png)

**Comment by yecli** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.25

**Comment by tatarincev** [comment]
The client got this picture after the update catalog module to the 2.23.25 version
![image](https://user-images.githubusercontent.com/7566324/69251068-7b143a80-0bb9-11ea-9664-26de4adc536d.png)

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/69252194-4a350500-0bbb-11ea-948e-051fa5de261c.png)
This is the result on my local machine with the latest module version

**Comment by yecli** [comment]
Closing, as all PRs are merged:
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.55
https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.32
