### ISSUE TITLE
CatalogSearchServiceImpl sometimes returns all categories, even when specific catalogId specified

### ISSUE THREAD

**Issue by lordstyx** [VirtoCommerce/vc-module-catalog#26]
Steps to reproduce:
Create a few catalogs with each some categories. They don't have to contain products.
Then make a final catalog, but don't create categories in it.

Then, using the following search criteria, invoke the service's Search method

```
var _searchService = _container.Resolve<ICatalogSearchService>();
var criteria = new SearchCriteria
{
	CatalogId = catalog.Id,
	ResponseGroup = SearchResponseGroup.WithCategories,
	SearchInChildren = true,
	WithHidden = true
};
var foundCategories = _searchService.Search(searchCriteria).Categories;
```

You'll find that all categories created in the other catalogs are returned.

Because `if (criteria.SearchInChildren)` ( [on line 95](https://github.com/VirtoCommerce/vc-module-catalog/blob/master/VirtoCommerce.CatalogModule.Data/Services/CatalogSearchServiceImpl.cs#L95) ) is true, the catalogId filter ( like [on line 108](https://github.com/VirtoCommerce/vc-module-catalog/blob/master/VirtoCommerce.CatalogModule.Data/Services/CatalogSearchServiceImpl.cs#L108) ) is never set.

**Comment by asvishnyakov** [comment]
Possible not a bug. @tatarincev May confirm?

**Comment by tatarincev** [comment]
property CatalogIds implicitly populated with CatalogId property value
