### ISSUE TITLE
How to speed up showing product on website, when it has more than thousand variation?

### ISSUE THREAD

**Issue by dku4cdm** [VirtoCommerce/vc-module-catalog#271]
**Description** 
I added an issue about “Cartesian product” #243  recently. I have avoided this problem and import all variations as intended, but as a result, some products with more than 400 variations are showing their variations in 5 seconds or more.

Please, help, how can I speed up loading the variations to show?

**Comment by tatarincev** [comment]
@dku4cdm  Could you clarify where do have these problems? On the platform manager or on the storefront?

**Comment by dku4cdm** [comment]
@tatarincev this problem has occurred on the storefront side. I resolved it when a decreased amount of variations. But an error is still presented if the total amount of variations for one product in average is bigger than 8 thousand.

**Comment by tatarincev** [comment]
@dku4cdm Excuse us  for delay with reply.
I understand you problem, and there are my recommendations:

- Do not load product with all it variations, You can control this by [ItemResponseGroup](https://github.com/VirtoCommerce/vc-module-core/blob/dev/VirtoCommerce.Domain/Catalog/Model/ItemResponseGroup.cs)
Call the  load product  API with response group without `Variations` flag

```C#
IItemService.GetById(id, ItemResponseGroup.Full & ~ItemResponseGroup.Variations)
```
or in storefront theme Liquid template

```liquid
{% paginate collection.products by 5 params {"ResponseGroup":"ItemInfo <-- set manually what exactly product dependencies you went to load on this page "} %}
   {% for product in collection.products%}
     ....
   {% endfor %}
{% endpaginate %}
```

- Load product variations by separated query
https://github.com/VirtoCommerce/vc-module-catalog/issues/233
