### ISSUE TITLE
Ability to use image URLs as product images directly without uploading it to the storage

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-catalog#279]
Need to have an ability to use image URLs as product images directly without uploading it to the storage.
![image](https://user-images.githubusercontent.com/15610352/66987002-52d87e00-f0d9-11e9-843b-f3eceb62b35a.png)

We could add "fa-external-link" icon before "+" with title "Use image from URL", that will save asset URL without uploading it.

**Comment by tatarincev** [comment]
Merged and released in https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.29 but due to that some UX improvement still pending we postpone the including this functionality in the release notes

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.31
