### ISSUE TITLE
Catalog UI doesn't show variation if Store visible disabled

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-catalog#299]
Version info: 
- Browser version: Chrome 78
- Platform version: 2.13.52
- Module version: 2.23.27

### Expected behavior
Variations should appear in admin UI always

### Actual behavior
Variations disappear if Store visible disabled

### Steps to reproduce
1. Create product
2. Add variation
3. Unselect Store visible
4. Variation will magically disappear from widget & list

**Comment by kostyrin** [comment]
![image](https://user-images.githubusercontent.com/8361000/70913625-11077d80-201f-11ea-930d-2537d6247a04.png)
platform 2.13.53
catalog 2.23.31
can't reproduce, maybe need to update

**Comment by asvishnyakov** [comment]
@kostyrin Disable Store visible for variation itself

**Comment by asvishnyakov** [comment]
@kostyrin Pay attention please. Try reproduce again

**Comment by kostyrin** [comment]
@asvishnyakov sorry I am not in the Operations
