### ISSUE TITLE
Assets from product not removed when product itself is removed?

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-module-catalog#3]
Hi,

When a product is removed from the catalog, it's assets aren't deleted as well. Is this by design? Any thoughts?

**Comment by tatarincev** [comment]
Yes, it's made by design, are you want to delete assets with product too?

**Comment by jvdonk** [comment]
Well, what's the use case for keeping them? Could assets be shared by products, in virtual catalogs maybe?

If there is no reason to keep them, they should be removed right?

**Comment by tatarincev** [comment]
Yes agree. I created issue associated with this on main platform rep.
https://github.com/VirtoCommerce/vc-platform/issues/717
