### ISSUE TITLE
Configurable storage blob provider path for store product images

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#30]
We should use folder path  
[CATALOG_CODE]/[PRODUCT_SKU]
when upload image to blob - File and Azure providers. 

@tatarincev commented on [Thu Jun 16 2016](https://github.com/VirtoCommerce/vc-platform/issues/512)

Currently new images uploaded to  storage path with product.code name. need to create some special setting which will be used for generate  storage path.
Some like this: {catalog}_{product.code}

**Comment by n2pro** [comment]
Extended path for storing an image for a product
[catalog]/[category.code][product.code] or [catalog]/[product.code]

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.6
