### ISSUE TITLE
It is impossible to remove many products from the catalog

### ISSUE THREAD

**Issue by vladimir-buravlev** [VirtoCommerce/vc-module-catalog#315]
It is impossible to remove many products from the catalog - when I select a large number of products and try to delete them, system gives 404 error without explanation.
Step 1: Check 100 Items in Catalog.
Step 2: Click "Delete" and confirm my intention.
Expected Result: Products will be removed.
Actual result: 404 error without details.

I suppose that the problem is that the identifiers of deleted objects are passed as query parameters and URI cannot handle such a long string.
\vc-module-catalog\VirtoCommerce.CatalogModule.Web\Controllers\Api\CatalogModuleProductsController.cs
--ln.291 -> public IHttpActionResult Delete([FromUri] string[] ids)

Platform version: 2.13.49
Catalog module version: 2.23.22

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.34
Added endpoint POST `/api/catalog/listentries/delete` allowing to delete batches of products/categories. You could specify search criteria conditions, or criteria.ObjectIds for deleting by ids.
