### ISSUE TITLE
ProductSearchCriteria missing Terms field in v3

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-catalog#338]
In v2 I used to be able to set terms for search like this:

```
                var criteria = new ProductSearchCriteria();
                criteria.Terms = new[] { string.Format("name:{0}", name) };
```
to search results by terms, why was it removed and what is the equivalent?

**Comment by akak1977** [comment]
It was moved to CatalogIndexedSearchCriteria.
https://github.com/VirtoCommerce/vc-module-catalog/blob/344194af092227716fcdf21d0d9aa87d246d6f46/src/VirtoCommerce.CatalogModule.Core/Model/Search/Indexed/CatalogIndexedSearchCriteria.cs#L7

**Comment by Woland2k** [comment]
Why ProductSearchCriteria still remains, it probably should be inherited from CatalogIndexedSearchCriteria?

**Comment by Woland2k** [comment]
@tatarincev any update? for the CMS integrated service I need to be able to search within sql database for the product by the ID passed from 3rd party cms.

**Comment by tatarincev** [comment]
We didn't support the search by  `terms` in the database before, because `terms` may contain some logical operators and has a special syntax that required a lexers analysis and convert it into a relevant to an index engine syntax tree. 
But we can add simply search by matching properties values  into the current implementation.

**Comment by Woland2k** [comment]
@tatarincev I had this code:

`                var criteria = new ProductSearchCriteria();
                criteria.Terms = new[] { string.Format("contentfulid:{0}", entry.Id) };
                var result = _productSearchService.SearchAsync(criteria).Result;

                if (result.TotalCount > 0)
                {
`

how do i convert this to 3.0?

**Comment by Woland2k** [comment]
It should be instead:

```
var criteria = new ProductIndexedSearchCriteria();
criteria.Terms = new[] { string.Format("contentfulid:{0}", entry.Id) };
var result = _productSearchService.SearchAsync(criteria).Result; // where _productSearchService is IProductIndexedSearchService

            if (result.TotalCount > 0)
            {
```
