### ISSUE TITLE
Catalog pagination is missing in the catalog overview page (v3)

### ISSUE THREAD

**Issue by zhangpengchen** [VirtoCommerce/vc-module-catalog#348]
When there is more than 20 catalogs, could not see them under `/#/workspace/catalog`, missing a catalog pagination in the page.

Version info: 
- Browser version: Chrome
- Platform version: 3.0.0-rc.4.232
- Module version: 3.0.0

**Comment by yecli** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-catalog/pull/349.
Release: https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.0.2
