### ISSUE TITLE
Add ability to overwrite title, description and SEO link for products

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#36]
@Woland2k commented on [Wed Feb 01 2017](https://github.com/VirtoCommerce/vc-platform/issues/719)

Since same product can be displayed by multiple sites, each site needs a slightly different description, product name and SEO link for a product to make SEO optimized.

**Comment by OlegoO** [comment]
We can configure SEO for catalog.
Need deside how to overwrite title, description

**Comment by tatarincev** [comment]
I think we may use the same approach as described in this article  
https://community.virtocommerce.com/t/how-to-make-product-name-localizable/88
