### ISSUE TITLE
Should copy only product and variations property from category 

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-module-catalog#39]
### Expected behavior
Should copy only product and variations properties from category 

### Actual behavior
Copy all properties from category 

https://github.com/VirtoCommerce/vc-module-catalog/blob/416e5b5e8a299c57673e3c4868b1e133a79ad578/VirtoCommerce.CatalogModule.Data/Services/ItemServiceImpl.cs#L281

**Comment by OlegoO** [comment]
Technical Implementation: 
Don't add Category and Catalog properties into __content

**Comment by artem-dudarev** [comment]
Fixed by 7724d5bb4ec074a2334d3ae5af09f8c13f9240f7

**Comment by artem-dudarev** [comment]
Released: https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.19.3
