### ISSUE TITLE
Add hints about priority order

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-catalog#43]
In gitter client says:

> I was playing around with the pricelist, and if i'm correct. The higher priority on Pricelist assignment get chosen to be used first. But on Item images the lowest priority is used first. It took me a while to figure it out with the pricing. I don't know if this is an issue, but maybe there should be some small "hint" text

I think it's good idea to add small hint about priority order (asc or desc) anywhere in products

**Comment by megafreeman** [comment]
@asvishnyakov Aleksander, I added a hint about priority in catalog assignment blade as shown in the pic below. Where else would you like to add other hints?

![image](https://user-images.githubusercontent.com/7536694/31126652-b2e2d6ce-a84c-11e7-9695-7c4a7b4456f2.png)

**Comment by asvishnyakov** [comment]
@megafreeman The most important thing is what we have different behaviors for priority. I.e. lowest first in one place, highest first in other. I think we need to determine what's primary (lowest or highest) and change others to primary behavior or  mark them with hints. But it need to be discussed.
@tatarincev @OlegoO What's your opinion?

**Comment by artem-dudarev** [comment]
There are different fields with different meaning.
PricelistAssignment has Priority, highest first.
CatalogImage has SortOrder, lowest first.

**Comment by megafreeman** [comment]
Another variant of description text, thanks @artem-dudarev 
![image](https://user-images.githubusercontent.com/7536694/31233031-d1ea8a9e-a9eb-11e7-8a53-aeedf3f6fcba.png)

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-pricing #11](https://github.com/VirtoCommerce/vc-module-pricing/issues/11) via [**ZenHub**](https://www.zenhub.com/)

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-pricing #12](https://github.com/VirtoCommerce/vc-module-pricing/issues/12) via [**ZenHub**](https://www.zenhub.com/)
