### ISSUE TITLE
Order dictionary items in alphabetical order

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#44]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Any
- Module version: 2.19.3

### Expected behavior
In Admin UI, see that dictionary items are ordered by value

### Actual behavior
Display dictionary items as IS

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-catalog/commit/fe17f2a499ff95e9e777dde743643b7d438730a8

Before:
![beforecapture](https://user-images.githubusercontent.com/7639413/31019449-03bd0fc6-a530-11e7-960d-5019693dd74e.PNG)

After:
![aftercapture](https://user-images.githubusercontent.com/7639413/31019456-06d57f7c-a530-11e7-9aee-9b2a69c3884b.PNG)

**Comment by alex765022** [comment]
Reviewed on dev

**Comment by Woland2k** [comment]
@OlegoO don't we want to control ordering when the list is created instead of always ordering alphabetically? That way I can add most popular values on top.
