### ISSUE TITLE
Properties/Parent properties of categories with same name but different PropertyType are considered as same

### ISSUE THREAD

**Issue by senseii** [VirtoCommerce/vc-module-catalog#470]
If a Catalog has defined a Category property and Product property with the same name and same ValueType but different PropertyType they are considered as same when the Category is fetched (ResponseGroup.Full) and therefore only one is returned under Category.Properties (the one with PropertyType.Product).

While debugging I got to this line. If the additionalTypes parameters are removed both properties are returned as expected.
.\vc-module-catalog\src\VirtoCommerce.CatalogModule.Core\Model\Category.cs Ln 133
 var existProperty = Properties.FirstOrDefault(x => x.IsSame(parentProperty, PropertyType.Product, PropertyType.Variation)); 

Version info: 
- Browser version: Firefox 78.6.1, Google Chrome 88.0.4324.104
- Platform version: 3.39.0 
- Module version: 3.28.0

### Expected behavior
Both properties should be returned

### Actual behavior
Only one property is returned

### Steps to reproduce

1. Define two properties with same name and ValueType but different PropertyType (Category and Product) under Catalog Properties settings: 
- PropertyName: DisplayName, ValueType: ShortText, PropertyType: Category
- PropertyName: DisplayName, ValueType: ShortText, PropertyType: Product
2. Add a Category in the Catalog and set its Property DisplayName
3. Fetch Category using the api/catalog/categories/{id} endpoint or navigate to the Catalog->Category->Properties through the VirtoCommerce UI
4. Category with only one property (PropertyType.Product) will be returned

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6721 has been created

**Comment by corneliusmunz** [comment]
We found that issue while migrating from v2 to v3. In v2 the properties with same name but different type was not treated as "same"

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.30.0
