### ISSUE TITLE
No GTIN in product index

### ISSUE THREAD

**Issue by AkulovOleg** [VirtoCommerce/vc-module-catalog#483]
### Expected behavior
As an admin I would like to search products by GTIN, so I need to have GTIN in product index

### Actual behavior
No GTIN in product index

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7126 has been created

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/pull/485

**Comment by OlegoO** [comment]
@AkulovOleg  you can install the latest alfa release with the fix

**Comment by Vectorfield4** [comment]
Feature released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.35.0
