### ISSUE TITLE
Connection of accessories doesn't work for variant products

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#49]
Connection of accessories doesn't work for variant products. Works for basic and parents.
Why: So machines have complete accessories attached. Better customer service by listing all variants.

Version info: 
- Browser version: Any
- Platform version: Any
- Module version: v2.20.0

### Expected behavior
Connection of accessories doesn't work for variant products. Works for basic and parents.
Why: So machines have complete accessories attached. Better customer service by listing all variants.

![image](https://user-images.githubusercontent.com/7639413/31343877-4b283a0a-ad11-11e7-9d20-06a975d99ca7.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.2
