### ISSUE TITLE
Catalog module fails to load if Pricing module not installed.

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-module-catalog#51]
Catalog module doesn't have dependency to the Pricing module but if user installs Catalog module only to the clean platform without the Pricing module admin doesn't load with the error below:
![image](https://user-images.githubusercontent.com/5801579/31388515-0021e7ba-add7-11e7-9e71-c2201218f131.png)
[Screencast installing catalog module to the clean platform](http://recordit.co/wzAswkuHIJ)
Uninstalling Pricing module from the working platform configuration results the same error.
[Screencast uninstalling pricing module](http://recordit.co/baEXWk7Cy2)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.2
