### ISSUE TITLE
Cannot create property for Product

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-module-catalog#54]
Hi,

Steps to reproduce:
1. Click 'Manage' on catalog.
2. Add property for Category with Property name = "Display name" and Display name = "Display name".
3. Click 'Manage' on category inside the catalog from point 1. 
4. Add property for Product with Property name = "Display name" and Display name = "Display name". 

Expected result: I have property Display name on category and product level. 
Actual result: Property is not added to Products. Nothing happens.
If in step 4 I create a property named "test", save it and add another property with name and display name = "Display name" the 'test' property disappears.

Catalog module version: 2.19.2

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/issues/54
