### ISSUE TITLE
No longer displays item variations in the backend, it only shows the count

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-catalog#553]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Microsoft Edge 94.0.992.31
- Platform version: 3.82.0
- Module version: 3.66.0

### Expected behavior
List Item variations in backend

### Actual behavior
It no longer displays item variations in the backend, it only shows the count.

### Steps to reproduce
1. Login em backend
2. Go to Catalog
3. Open any item with Variations
4. Click in Variations
5. Now, window item variations show, but, de grid is empty and count is correct

![image](https://user-images.githubusercontent.com/20837564/135728316-71089147-87df-4512-b186-103e8f190ae6.png)

![image](https://user-images.githubusercontent.com/20837564/135728349-51664fe5-1a20-46b9-ab85-c8077f307ea6.png)

no error in brownse console

Platform Version
3.82.0
Installed Modules
VirtoCommerce.BulkActionsModule 3.3.0
VirtoCommerce.Cart 3.23.0
VirtoCommerce.Catalog 3.66.0
VirtoCommerce.CatalogCsvImportModule 3.26.0
VirtoCommerce.CatalogPublishing 3.8.0
VirtoCommerce.Content 3.13.0
VirtoCommerce.Core 3.23.0
VirtoCommerce.Customer 3.33.0
VirtoCommerce.Export 3.15.0
VirtoCommerce.ImageTools 3.13.0
VirtoCommerce.Inventory 3.19.0
VirtoCommerce.LuceneSearch 3.5.0
VirtoCommerce.Marketing 3.27.0
VirtoCommerce.Notifications 3.18.0
VirtoCommerce.Orders 3.41.0
VirtoCommerce.Payment 3.7.0
VirtoCommerce.Pricing 3.25.0
VirtoCommerce.Search 3.16.0
VirtoCommerce.Shipping 3.8.0
VirtoCommerce.Sitemaps 3.7.0
VirtoCommerce.Store 3.24.0
VirtoCommerce.Tax 3.8.0
CLR version
3.1.19
64-bit operating system
true
64-bit process
true

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7768 has been created

**Comment by OlegoO** [comment]
@JoseCaetanoNeto I could not reproduce the problem. 

![image](https://user-images.githubusercontent.com/7639413/135830036-d4f61689-a8ba-4fc1-ae84-a6d146d4487d.png)

Could you refresh the browser cache? or open in the private window?

Do you see any JavaScript error in the console?

**Comment by JoseCaetanoNeto** [comment]
I removed the localstorage in the browser and it works again. Thanks!!

**Comment by OlegoO** [comment]
you are welcome
