### ISSUE TITLE
Delete property values for all objects on  property deletion

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-catalog#57]
If I assign a property to all products in a category and delete this property, products who had a value on this property but is now empty will not be removed when you delete the category-assigned product property.

Probably solution:
To support both types of deletion behavior, we can ask the user before deleting how he wants to delete the property. Completely with all the values, or only a property meta description with preserving values of this property in objects.

**Comment by eMazeika** [comment]
new dialog:
![image](https://user-images.githubusercontent.com/5801549/31928320-680b08a6-b8a0-11e7-82e5-50569e19164f.png)

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.2
