### ISSUE TITLE
Item Associations are Not Editable

### ISSUE THREAD

**Issue by montanehamilton** [VirtoCommerce/vc-module-catalog#6]
Currently when you add an item association it can only then be deleted.

I'm planning on extending the associations, which are great, but need to add additional data to each association to drive some additional requirements.

Even now it would be nice to edit the quantity or tags without having to delete and re-add the association.
I would think a blade for this should be added and the link to the associated product should be on that instead off the current list.

I'm happy to help as I need to learn how to work on blades anyway as I'll need to extend the base blade once completed.

**Comment by tatarincev** [comment]
We include this requirements in our roadmap task https://github.com/VirtoCommerce/vc-platform/issues/678

**Comment by ksavosteev** [comment]
![image](https://user-images.githubusercontent.com/20122385/29109830-c98d7e4e-7ce4-11e7-8104-01d89992ac12.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.19.3
