### ISSUE TITLE
Add a new product property, 'ValueType' is 'DateTime' and 'Multi language' has been selected, the date picker does not show

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#61]
@zhangpeng-kooboo commented on [Thu Oct 27 2016](https://github.com/VirtoCommerce/vc-platform/issues/657)

When I add a new product property, 'ValueType' is 'DateTime' and 'Multi language' has been selected, the date picker does not shown.

---

@OlegoO commented on [Tue Sep 05 2017](https://github.com/VirtoCommerce/vc-platform/issues/657#issuecomment-327186231)

Multi language should not take affect to DateTime

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.4
