### ISSUE TITLE
Association tags not working

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-module-catalog#63]
it seems like tags are not being assigned to created/updated association. I checked the behavior with your online demo BO and is the same.
 
Steps to follow:
Enter any product details blade
Click association widget, Add
Select any product, pick type, enter quantity and value of tag, e.g. “MyTestTag”, the tag field is instantly highlighted in red
Click save on product’s blade
Re-enter association blade
 
Outcome is that tag is not saved. It seems like angular is not submitting the value to the backend, please find screenshot from dev tools attached.

![capture_vc_associations tag missing](https://user-images.githubusercontent.com/5917756/32037796-a510381c-ba2f-11e7-99e4-25c28dedd922.PNG)

**Comment by tatarincev** [comment]
This is a small UX inconvenience. Used there "tags-input" control required 'Enter' key press to confirm entered values.
![image](https://user-images.githubusercontent.com/7566324/32039168-5d2d6832-ba2d-11e7-98b2-a5b90856f8b8.png)

**Comment by IgorisB** [comment]
Control correctly shows red border (aka validation error) if value is not confirmed with Enter and focus moved to another field. However "Ok" button is active and user can save the blade, without tags in this case (see screenshot below).

So I see two solutions:
1) create tag optionally on focus lost
2) disable "Ok" if tag control has validation error

![image](https://user-images.githubusercontent.com/5917756/32042265-9e4de186-ba3f-11e7-87e1-f4474d6daca1.png)

**Comment by tatarincev** [comment]
I've changed 'tags-input' behavior to add-on-blur,  it will add a value at the time of the focus lost.

**Comment by asvishnyakov** [comment]
@tatarincev Platform already do this: https://github.com/VirtoCommerce/vc-platform/blob/fc8c617a4886c34fc0a9bc438fea903cda5d2c6c/VirtoCommerce.Platform.Web/Scripts/app/app.js#L209
Need to find reason why this setting is not applies to this tag input.

**Comment by eMazeika** [comment]
@asvishnyakov the value from Platform gets applied **if** it's not overridden in html explicitly

**Comment by asvishnyakov** [comment]
@eMazeika Good job! I didn't see what Eugeney just *change* false to true, I thought he *added* this value.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.4
