### ISSUE TITLE
Not restore sorting after reopen category blade

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-module-catalog#66]
I open list  of products blade, click label for sort by property(desc sort), product sorted. I then close this blade
![image](https://user-images.githubusercontent.com/14821555/32053963-1bcd9fb2-ba5d-11e7-8a49-6889b6fd946a.png)
I reopen this blade, but products not sorted by property and show sort label, for restore sorting need thre clicks by this property.
![image](https://user-images.githubusercontent.com/14821555/32054044-64947ed2-ba5d-11e7-86ad-09da769a684b.png)

**Comment by eMazeika** [comment]
@FreeKen thanks for reporting this. The fix should be included in the next VC Platform release. 
Meanwhile you can use a workaround: click "Refresh"after the initial data was loaded.
