### ISSUE TITLE
Product property

### ISSUE THREAD

**Issue by Anatfe** [VirtoCommerce/vc-module-catalog#662]
Product property with checkbox type is always edited. Field "isReadonly" does not work

Version info: 
- Browser version: Google Chrome v 109.0.5414.119
- Platform version: [3.270.0]
- Module version: 3.256.0

### Expected behavior
Property field is not editable

### Actual behavior
Property field is editable

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8301 has been created

**Comment by Anatfe** [comment]
￼

Hi.
I set field isReadOnly = true to some properties. These properties are view-only. 
But properties with the checkbox type are open for editing. "ng-disabled" tag is not used for the checkbox type in model VirtoCommerce.CatalogModule.Web/Scripts/directives/property2.tpl.html  

> 20 февр. 2023 г., в 10:03, Dan-BV ***@***.***> написал(а):
> 
> Could you please detail the steps for playback and attach the package.json file of the installed modules?

**Comment by Dan-BV** [comment]
Could you describe in more detail what you do?
