### ISSUE TITLE
Add StartDate and EndDate to product UI

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-catalog#67]
Currently index does add StartDate and EndDate for product, however there is no UI for those properties.

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.5

**Comment by Woland2k** [comment]
We should allow entering time as well as date for this.

**Comment by tatarincev** [comment]
We have another issue related to this requirement 
https://github.com/VirtoCommerce/vc-platform/issues/1204
