### ISSUE TITLE
Issue with properties when using validation pattern

### ISSUE THREAD

**Issue by mariusz-ba** [VirtoCommerce/vc-module-catalog#690]
Hi, I noticed a bug with catalog properties. Whenever I add new catalog property, mark it as "Multi value", "Multi language" and specify custom validation pattern - I'm not able to edit that property - even if provided value matches validation pattern.

Version info: 
- Browser version: Google Chrome 115.0.5790.114
- Platform version: 3.317.0
- Module version: 3.277.0

### Expected behavior

It should be possible to provide value that matches a pattern without seeing any validation errors. The "OK" button should not be disabled and user should be able to save changes.

### Actual behavior

When providing value that matches a pattern, input is cleared and error message appears. User is not able to save changes because "OK" button is disabled.

### Steps to reproduce

1. Create catalog property, mark it as "Multi value" and "Multi language".
2. Specify custom validation pattern.
3. Attempt to edit property value.

Here is a screenshot of property configuration and video with the actual behavior:

![catalog1](https://github.com/VirtoCommerce/vc-module-catalog/assets/9806693/ea9567fa-22da-4896-92c0-985e85833c3a)

![catalog2](https://github.com/VirtoCommerce/vc-module-catalog/assets/9806693/b21feae1-7b3e-44ea-83f3-994e6e871f5b)

### Note

We're migrating VC2 to VC3 and we have existing properties with validation pattern setup. The properties, their values, and validation rules are successfully fetched and are present in JSON response. However they are not correctly rendered on UI (all inputs are empty and have red outline indicating an error). This makes us unable to save any changes within the blade.

**Comment by OlegoO** [comment]
@mariusz-ba I added this issue into the current sprint. It should be resolved max in next two week. https://virtocommerce.atlassian.net/browse/PT-12888
