### ISSUE TITLE
Product startdate issue

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-module-catalog#72]
It seems product start date is not compared in UTC format: 
When adding new products, it appears the product's Start date is set to tomorrow by default. I get around this by simply modifying the value in the database to an earlier date time, otherwise it doesn't show up in the store until tomorrow

**Comment by tatarincev** [comment]
@asvishnyakov  could you be a reviewer on this issue?

**Comment by asvishnyakov** [comment]
@tatarincev It depends on when it will be complete. If not today/tomorrow then yes, I can.

**Comment by n2pro** [comment]
@IgorisB I could not reproduce a similar situation, we always have the UTC stored in the database, maybe after updating the date time picker, we'll see the start time of sales
