### ISSUE TITLE
Property values are not inherited from non-product parent

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-catalog#724]
I noticed that property and property values inheritance on products works in an unexpected way: it seems that while all properties are inherited from a product's line of ancestry up to the catalog, the values of those properties are only inherited if the parent is another product. This can be clearly seen in [code ](https://github.com/VirtoCommerce/vc-module-catalog/blob/480f6d9939b30634f00d4cc4c8c676c66359e25f/src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs#L306)- `CatalogProduct.InheritPropertyValues()` is called only from `InheritFromCatalogProduct()` which is a no-op when the parent is not a product.

Is this by design?

Version info: 
- Platform version: 3.800.12
- Module version: 3.803.0

### Expected behavior

`CatalogProduct` inherits property values from all types of ancestors: main products, categories and catalogs.

### Actual behavior

`CatalogProduct` inherits property values only from main products.

**Comment by OlegoO** [comment]
At this moment, it's by design. We will think how to improve UX to simplify clarification the inheritance from main product.
