### ISSUE TITLE
Drop the requirement for product associations search criteria to have at least one object id

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-catalog#738]
Currently `ProductAssociationSearchService` [requires](https://github.com/VirtoCommerce/vc-module-catalog/blob/179c2e309290a65c1f1c9aa90574645a4bac7c46/src/VirtoCommerce.CatalogModule.Data/Search/ProductAssociationSearchService.cs#L38) that the search criteria has at least one item in `ProductAssociationSearchCriteria.ObjectIds`, otherwise the search result is an empty set. From my understanding of the code, `ObjectIds` are used as criteria on `Association.ItemId` column, but sometimes I want to search by 
 `Association.AssociatedItemId` instead. I know that `ProductAssociationSearchCriteria` has the `AssociatedObjectIds` property, but still I have to provide non-empty `ObjectIds` for the search to actually happen. Is there a reason for that? If not, can this requirement be relaxed for example to non-empty `ObjectIds` *or* `AssociatedObjectIds`?

**Comment by OlegoO** [comment]
@j-mok  Created PR with fix https://github.com/VirtoCommerce/vc-module-catalog/pull/741

**Comment by OlegoO** [comment]
Fixed with https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.818.0
