### ISSUE TITLE
How to get rid of duplicated data?

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-module-catalog#77]
Hi,I'd search something,and search request struct like that:
{
  "size" : 0,
  "aggs": {
          "distinct_propname" : {
              "terms" : {
                "field" : "propname",
                "size":100
              }
          }
        }
  }
}
what should I do?Can it be realized?

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
