### ISSUE TITLE
Wrong permission checking for catalog:read permission

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-catalog#8]
Platform version: 2.13.8
Module version:  2.16.7

### Expected behavior:
1. When user has no `catalog:read` permission, he/she must be *unable to view catalog, categories* and products inside them.
2. When `catalog:read` permission assigned and *no scopes* assigned, use must be able to view *all catalogs, categories* and products inside them.
3. When `catalog:read` permission assigned, catalog scope assigned and categories scope not assigned, user must be able to view *only selected catalogs* and categories inside them.
4. When `catalog:read` permission assigned, catalog scope not assigned and categories scope assigned, user must be able to view *only selected categories* and all catalogs, which contains this categories.
5. When `catalog:read` permission assigned, catalog scope assigned and categories assigned, user must be able to view *only selected categories in selected catalogs* (intersection).

### Actual behavior:
1. Works as expected.
2. Works as expected.
3. User is able to view only selected catalogs, but *every* catalog contains root and/or nested categories from *all available to user catalogs.* Also, if you try to open product page, you will receive 401 error.
4. User is able to view *all* catalogs, but *every* catalog contains nested categories from *all available to user categories* and/or products from them. Also, user can't open any category.
5. User is able to view only selected catalogs, but *every* catalog contains nested categories from *all categories assigned to scope* and/or products from them. Also, user can't open any category.

### Steps to reproduce
1. Create new user *(test user)* without permissions and administrator rights.
2. Create new role (*test role*) and assign `catalog:access` and `catalog:read` permissions to it.
3. Assign *test role* to *test user*.
4. Assign security scope to `catalog:access` permission in *test role*, restart IIS (VirtoCommerce/vc-platform#732) and login to platform using *test user* account. The following security scopes affected:
4.1. `Only for selected catalogs`
4.2. `Only for selected categories`
4.3. Combination of this scopes

This issue possible caused by this code (file `VirtoCommerce.CatalogModule.Web.Core\Security\SearchCriteriaExtensions.cs`):

``` csharp
public static class SearchCriteriaExtensions
{
    public static void ApplyRestrictionsForUser(this SearchCriteria criteria, string userName, ISecurityService securityService)
    {
        // Check global permission
        if (!securityService.UserHasAnyPermission(userName, null, CatalogPredefinedPermissions.Read))
        {
            // Get user 'read' permission scopes
            var readPermissionScopes = securityService.GetUserPermissions(userName)
                .Where(x => x.Id.StartsWith(CatalogPredefinedPermissions.Read))
                .SelectMany(x => x.AssignedScopes)
                .ToList();

            var catalogScopes = readPermissionScopes.OfType<CatalogSelectedScope>();
            if (catalogScopes.Any())
            {
                // Filter by selected catalog
                criteria.CatalogIds = catalogScopes.Select(x => x.Scope)
                                                    .Where(x => !string.IsNullOrEmpty(x))
                                                    .ToArray();
            }

            var categoryScopes = readPermissionScopes.OfType<CatalogSelectedCategoryScope>();
            if(categoryScopes.Any())
            {
                // Filter by selected categories
                criteria.CategoryIds = categoryScopes.Select(x => x.Scope)
                                                        .Where(x => !string.IsNullOrEmpty(x))
                                                        .ToArray();
            }
              
        }
    }
}
```

**Comment by asvishnyakov** [comment]
@Woland2k I've unassigned @tatarincev, assign some else, please

**Comment by tatarincev** [comment]
I think this `artificial complexity` was introduced by `categories` permission scope along with `catalog` scope. In the platform 3.0 we opted-out `categories` scope from catalog permissions and this problem no longer relevant. Only the scope of the `catalog`  is simpler and closer to real-world cases.
![Uploading image.png…]()
