### ISSUE TITLE
Add "Geo-point" product's property type

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#86]
As a product manager, I want to save Geo-point information as property.

### Acceptance criteria
- [ ] GIVEN Product, Category, Catalog properties
WHEN I click add property and open a new property blade
THEN I should see Geo-point as one of Value types.

### Definition of Done
- [ ] Use resource localization
- [ ] Code review
- [ ] Documentation

![image](https://user-images.githubusercontent.com/7639413/33819284-439aeb94-de52-11e7-856d-0769cd7ea2f8.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.0
