### ISSUE TITLE
Load, Edit and Save "Geo-point" property value

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#87]
As a catalog manager, I want to edit and save geo-point information.

### Acceptance criteria
- [ ] GIVEN Item(Product, Category or Catalog) with geo-point property
WHEN I open properties blade
THEN I should see geo-point property value in "41.12,-71.34" format

- [ ] GIVEN Item with geo-point property
WHEN I edit geopoint value and set wrong value (value doesn't match to regex below) and try to save
THEN I should see validation error
 
"^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$"
from 
https://stackoverflow.com/questions/3518504/regular-expression-for-matching-latitude-longitude-coordinates

- [ ] GIVEN Item with geo-point property
WHEN I edit geopoint value, set correct value and try to save
THEN I should see OK

### Definition of Done
- [ ] Geo-point should use PropertyValue table and ShortTextValue column as persistent storage.
- [ ] Check Catalog, Category  and Product
- [ ] Check multi language mode
- [ ] Check dictionary mode
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.0
