### ISSUE TITLE
There is no validation when adding a new dictionary type property

### ISSUE THREAD

**Issue by n2pro** [VirtoCommerce/vc-module-catalog#92]
When adding a new property for integer and other properties no validation adding values to the dictionary
![capture](https://user-images.githubusercontent.com/13115017/34095778-75c4dfba-e3db-11e7-80c4-de723e10ef2a.JPG)

**Comment by tatarincev** [comment]
The blade for managing the property dictionary
![image](https://user-images.githubusercontent.com/7566324/36794353-c1be3a3c-1ca8-11e8-8a6d-88ad2e0a0cd8.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.0
