### ISSUE TITLE
Virtual catalog should have ability to select Additional languages

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-catalog#93]
Virtual catalog should provide ability to select Additional languages as well as physical catalog. 
I want to create localized  Display Name property for virtual category.
 
Version info: 
- Module version: v2.20.8

### Expected behavior
Virtual catalog should provide ability to select Additional languages

![image](https://user-images.githubusercontent.com/7639413/34340136-3aa012ae-e987-11e7-9490-49ecf7ca9e9a.png)

### Actual behavior
Now, I can select Default language only

![image](https://user-images.githubusercontent.com/7639413/34340140-43e94fba-e987-11e7-83f3-9b80995ab5cd.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.21.0
