### ISSUE TITLE
NOT is search phrase query

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-module-catalog#99]
Is it possible to use Lucene NOT is search phrase on catalog blade? Could you give me some examples?

**Comment by artem-dudarev** [comment]
The search phrase syntax is not a Lucene syntax, and current phrase parser doesn't suport logical operators (yet).

**Comment by danielstarzewski** [comment]
@artem-dudarev thank you for you reply. Are you planning to extend the syntax in near future?

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-47
